config/routes.rb
SampleApp::Application.routes.draw do

  root 'static_pages#home'
  
  get '/signup',  to: "users#new"
  
  get '/help',    to: "static_pages#help"
  get '/about',   to: "static_pages#about"
  get '/contact', to: "static_pages#contact"

  get '/signin',  to: "sessions#new"
  delete '/signout',  to: "sessions#destroy"

  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :microposts, only: [:create, :destroy]

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
	
	belongs_to :user
	default_scope -> { order('created_at DESC') }
	validates :user_id, presence: true
	validates :content, presence: true, length: { maximum: 140 }

end

app/models/user.rb
class User < ActiveRecord::Base

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

	has_many :microposts, dependent: :destroy

	validates :name, presence: true, length: { maximum: 50 }
	validates :email, presence: true, uniqueness: { case_sensitive: false }, format: {with: VALID_EMAIL_REGEX }
	validates :password, length: { minimum: 6 }

	has_secure_password

	before_create :create_remember_token
	before_save { email.downcase! }

	def feed
		Micropost.where("user_id = ?", id);
	end

	def self.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def self.encrypt(string)
		Digest::SHA1.hexdigest(string.to_s)
	end

	private 

	def create_remember_token
		self.remember_token = User.encrypt(User.new_remember_token)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper
  add_flash_types :error, :success
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController

	before_action :signed_in_user, only: [:create, :destroy]
	before_action :correct_user, only: :destroy

	def create
		
		@micropost = current_user.microposts.build(micropost_params)
		if @micropost.save
			redirect_to root_path, success: "Micropost created!"
		else
			@feed_items = current_user.feed.paginate(page: params[:page])
			render 'static_pages/home'
		end

	end

	def destroy
		@micropost.destroy
		redirect_to root_path
	end

	private

	def micropost_params
		params.require(:micropost).permit(:content)
	end

	def correct_user
		@micropost = current_user.microposts.find_by(id: params[:id])
		redirect_to root_path if @micropost.nil?
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
		
	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			sign_in user
			redirect_back_or user
		else
			flash.now[:error] = "Invalid email/password combination"
			render :new
		end
	end

	def destroy
		sign_out current_user
		redirect_to root_path
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
  	  @micropost = current_user.microposts.build
  	  @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  def new
  	@user = User.new
  end

  def show
  	@user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      sign_in @user
  		redirect_to @user, success: "Welcome to the Sample App"
  	else
  		render :new
  	end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      redirect_to @user, success: "Profile updated"
    else
      render 'edit'
    end
  end 

  def destroy
    user = User.find(params[:id])
    if !current_user?(user)
      user.destroy
      redirect_to users_path, success: "User deleted."
    else
      redirect_to users_path, notice: "You can't delete yourself!"
    end
  end

  private 

  def user_params
  	params.require(:user)
  	      .permit(:name, :email, :password, :password_confirmation)
  end

  def correct_user 
    @user = User.find(params[:id])
    redirect_to root_path unless current_user?(@user)
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title( page_title="" )
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

  def flash_class(level)
    case level
        when :notice then "alert alert-info"
        when :success then "alert alert-success"
        when :error then "alert alert-danger"
        when :alert then "alert alert-warning"
    end
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper

  def wrap(content)
    sanitize(raw(content.split.map{ |s| wrap_long_string(s) }.join(' ')))
  end

  private

    def wrap_long_string(text, max_width = 30)
      zero_width_space = "&#8203;"
      regex = /.{1,#{max_width}}/
      (text.length < max_width) ? text :
                                  text.scan(regex).join(zero_width_space)
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def current_user=(user)
		@current_user = user
	end

	def current_user
		remember_token = User.encrypt(cookies[:remember_token])
		@current_user ||= User.find_by(remember_token: remember_token)
	end

	def current_user?(user)
		user == current_user
	end

	def sign_in(user)
		remember_token = User.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		#update_attribute bypasses validations, we don't have passwords
		user.update_attribute(:remember_token, User.encrypt(remember_token))
		self.current_user = user
	end

	def sign_out(user)
		current_user.update_attribute(:remember_token, 
								 User.encrypt(User.new_remember_token))
		cookies.delete(:remember_token)
		self.current_user = nil
	end

	def signed_in?
		!current_user.nil?
	end

	def redirect_back_or(default)
		redirect_to(session[:return_to] || default)
		session.delete(:return_to)
	end

	def store_location
		session[:return_to] = request.url if request.get?
	end
	
	def signed_in_user
	  unless signed_in?
	    store_location
	    redirect_to signin_path, notice: "Please Sign In"
	  end
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

	def gravatar_for(user, options = { size: 50 })
		id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		url = "https://secure.gravatar.com/avatar/#{id}?s=#{size}"
		image_tag url, alt: user.name, class: "gravatar"
	end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
 <header class="navbar navbar-fixed-top navbar-inverse" role="navigation">
   <div class="container">
     <div class="navbar-header">
       <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#nav">
         <span class="sr-only">Toggle navigation</span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
       </button>
       <%= link_to "Sample App", root_path, id: 'logo' %>
     </div>
     <nav class="collapse navbar-collapse" id="nav">
       <ul class="nav navbar-nav navbar-right">
         <li><%= link_to "Home", root_path %></li>
         <li><%= link_to "Help", help_path %></li>
         <% if signed_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="drowndown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"</li>
              <li><%= link_to "Sign Out", signout_path, method: "delete" %></li>      
            </ul>   
          </li>
        <% else %>
          <li><%= link_to "Sign In", signin_path %></li>
         <% end  %>
       </ul>
     </nav>
   </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body> 
  	<%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: flash_class(key)) %>
      <% end %>
      <%= yield %>   
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
</body>
</html>

app/views/microposts/_micropost.html.erb
<li>
	<span class="content"><%= wrap(micropost.content) %></span>
	<span class="timestamp">
		Posted <%= time_ago_in_words(micropost.created_at) %> ago.
	</span>
	<% if current_user?(micropost.user) %>
		<%= link_to "delete", micropost, method: :delete,
			data: { confirm: "You sure?"},
			title: micropost.content %>
	<% end %>
</li>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
	<div class="alert alert-danger">The form contains <%= pluralize(object.errors.count, "error") %></div>
	<ul>
		<% object.errors.full_messages.each do |msg| %>
		<li>* <%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  <span class="user">
    <%= link_to feed_item.user.name, feed_item.user %>
  </span>
  <span class="content"><%= wrap(feed_item.content) %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
  </span>
  <% if current_user?(feed_item.user) %>
  	<%= link_to "delete", feed_item, method: :delete,
  		data: { confirm: "You sure?"},
  		title: feed_item.content %>
  <% end %>
</li>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<div class="row">
		<div class="form-group col-sm-12">
			<%= f.text_area :content, placeholder: 'Compose new micropost...',  class: "form-control", maxlength: 140 %>
		</div>
	</div>
	<div class="row">
		<div class="form-group col-sm-12">
			<p>You have <span id="char-count">140</span> characters left.</p>
		</div>
	</div>
	<div class="row">
		<div class="form-group col-sm-6 col-sm-offset-6">
	<%= f.submit "Post", class: "btn btn-block btn-primary" %>
		</div>
	</div>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 58), current_user %>
<h1><%= current_user.name %></h1>
<div><%= link_to "view my profile", current_user %></div>
<div><%= pluralize(current_user.microposts.count, "micropost") %></div>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About Us</h1>
<p>
  The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/static_pages/home.html.erb
<% if signed_in? %>
<div class="row">
	<aside class="col-sm-5">
		<section class="user-info"><%= render 'shared/user_info' %></section>
		<section class="micropost-form"><%= render 'shared/micropost_form' %></section>
	</aside>
  <div class="col-sm-7">
    <h3>Micropost Feed</h3>
    <%= render 'shared/feed' %>
  </div>
</div>
<% else %>
<div class="center jumbotron">
  <h1>Welcome to the Sample App</h1>
  <h2>
    This is the home page for the
    <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>
  <%= link_to "Sign up now!", signup_path, class: 'btn btn-large btn-primary' %>
</div>
<%= link_to image_tag("rails.png", alt: 'rails'), 'http://rubyonrails.org' %>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>	
	<div class="row">
		<div class="form-group col-sm-6">
			<%= f.label :name, class: 'control-label' %>
			<%= f.text_field :name, class: 'form-control' %>
		</div>
		<div class="form-group col-sm-6">
			<%= f.label :email, class: 'control-label'  %>
			<%= f.email_field :email, class: 'form-control' %>
		</div>
	</div>
	<div class="row">
		<div class="form-group col-sm-6">
			<%= f.label :password, class: 'control-label'  %>
			<%= f.password_field :password, class: 'form-control' %>
		</div>
		<div class="form-group col-sm-6">
			<%= f.label :password_confirmation, "Password Confirmation", class: 'control-label'  %>
			<%= f.password_field :password_confirmation, class: 'form-control' %>
		</div>
	</div>
	<div class="row">
		<div class="form-group col-sm-6">
			<%= f.submit button_text, class: "btn btn-large btn-primary" %>
		</div>
	</div>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
  	| <%= link_to "delete", user, method: :delete, data: { confirm: "You sure?" } %>
	<% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'Edit User') %>
<h1>Update your profile</h1>

<div class="row">
	<div class="form-group col-sm-6">
	<%= gravatar_for @user, size: 100 %>
	<a href="http://gravatar.com/emails">change</a>
	</div>
</div>

<%= render partial: 'form', locals: {button_text: 'Save Changes'} %>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users  %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<%= render partial: 'form', locals: {button_text: 'Create My Account'} %>

app/views/users/show.html.erb
<%= provide(:title, @user.name) %>

<div class="row">
	<aside class="col-sm-4">
		<section class="user-info">
			<h1>
				<%= gravatar_for @user %>
				<%= @user.name %>
			</h1>
		</section>
	</aside>
	<div class="col-sm-8">
	    <% if @user.microposts.any? %>
	      <h3>Microposts (<%= @user.microposts.count %>)</h3>
	      <ol class="microposts">
	        <%= render @microposts %>
	      </ol>
	      <%= will_paginate @microposts %>
	    <% end %>
	  </div>
</div>